# General
title: Kazaja Feriya
description: Abenduak 16 Diciembre - Mosku
author:
  name: Iune Trecet Obeso
  email: contact@iune.info
  github: iunetrecet
  web: http://iune.info
timezone: "Europe/Paris


